### ISSUE TITLE
Make sure the latest release label is assigned based on semantic versioning

### ISSUE THREAD

**Issue by nyechiel** [submariner-io/releases#787] opened 2023-07-06 19:25 UTC
Originally discussed in this Slack thread: https://kubernetes.slack.com/archives/C010RJV694M/p1688669181906819

For some reason, it looks like 0.14.6 was labeled as "latest release", while we also have 0.15.2 released. This resulted in users running `curl -Ls https://get.submariner.io | bash` getting 0.14.6, and not 0.15.2 as expected (at this point of time).

I manually fixed it for now by editing the 0.15.2 release page and labeling it as the latest, but we need to review our release process and make sure we always mark the latest release based on semantic versioning and not the release date.

**Comment by skitt** [comment] 2023-07-07 07:03
Duplicate of https://github.com/submariner-io/releases/issues/573

**Closed as not planned by skitt** 2023-07-07 07:03 UTC
